Replaceable notifications
iamkroot/trakt-scrobbler pull request #103
Opened 2021-01-15 15:33 UTC by ahmubashshir

Replaceable notifications using dbus

- Use `SessionBus` from pydbus to send replaceable notification using
  `org.freedesktop.Notifications.Notify`
- Remove pygobject dependency.

2021-01-15 15:59 UTC, iamkroot commented
Thanks for the PR! Using `SessionBus` instead of `PyGObject` looks great! That should really tone down the dependency size.

2021-01-15 16:03 UTC, ahmubashshir commented
btw... notify me when you release new version... I'll have to update 
the optdepends in pkgbuild manually (I'm using a script to update 
pkgver with systemd timer).

On Fri, Jan 15, 2021 at 07:59, Krut Patel <notifications@github.com> 
wrote:
> Thanks for the PR! Using SessionBus instead of PyGObject looks great! 
> That should really tone down the dependency size.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/iamkroot/trakt-scrobbler/pull/103#issuecomment-761026580>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AF5WM3SY6TOLFMVGATM3QMTS2BQ6XANCNFSM4WEG7OQQ>.
>

2021-01-15 16:04 UTC, iamkroot requested changes
I'm not a fan of modifying the global variables using the `globals()` object. Rather, I'd prefer explicitly using the `global` keyword for such variables. 
Secondly you're using `_some_var_ in globals()` to test if the variable is defined. It is much cleaner and clearer to use `_some_var_ is not None` test for this - similar to how `notifier` variable was used earlier.

2021-01-15 16:04 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> +ENABLE_NOTIFS = config['general']['enable_notifs'].get(
`ENABLE_NOTIFS` should be in lowercase. It is not a global constant. It's value is changed in case sending the notification raises an error.

2021-01-15 16:04 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
Considering that the logic for linux notifications is quite long, it would be better to keep this function.

2021-01-15 16:04 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> +            NOTIF_ID = 0
Should be lowercase. It's value is updated.

2021-01-15 16:04 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> +            NOTIFIER = SessionBus().get('.Notifications')
Should be lowercase. It is not a simple constant (like an int or a string), but a complex object. I would prefer `Notifier`.

2021-01-15 16:14 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> +            NOTIFIER = SessionBus().get('.Notifications')
what about `__notifier` ?

2021-01-15 16:15 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> +ENABLE_NOTIFS = config['general']['enable_notifs'].get(
How about renaming it to `__enable_notifs` as it is private variable?

2021-01-15 16:17 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> +            NOTIFIER = SessionBus().get('.Notifications')
Nope, it's not something we want to hide either (dunders are reserved for private vars). Looking at how `toaster` is defined for windows, I think `notifier` will also do fine.

2021-01-15 16:19 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> +            NOTIFIER = SessionBus().get('.Notifications')
ok.

2021-01-15 16:22 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> +ENABLE_NOTIFS = config['general']['enable_notifs'].get(
I haven't seen dunder in variable names being used at the module level. The concept of private variables only really applies to classes (If you need to specify private vars for modules, you should be using classes). And even if we want to apply it here, I don't think `enable_notifs` should be a private variable. In a hypothetical scenario, if some other module uses the `notifier.py` module, toggling the notifications on/off should very much be exposed to it.

2021-01-15 16:23 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> +ENABLE_NOTIFS = config['general']['enable_notifs'].get(
:3.

2021-01-15 16:27 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
dbus is not linux specific[1] so we can include it here

[1]: https://www.freedesktop.org/wiki/Software/dbus/

2021-01-15 16:27 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> +            NOTIF_ID = 0
ok

2021-01-16 05:28 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
But we're only using the API for notifications on linux. That's why it's necessary to mark it as such.

2021-01-16 20:10 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
ok

2021-01-16 20:13 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
btw... *bsds used dbus for notifications too.

2021-01-17 03:52 UTC, iamkroot commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
Ah you're right, forgot about that 😅

2021-01-17 04:46 UTC, ahmubashshir commented on trakt_scrobbler/notifier.py
> -def notify_linux(body, title=APP_NAME, timeout=5):
Then we shouldn't move it to another function, should we?

2021-01-17 05:05 UTC, iamkroot commented
There's some trouble in my setup it seems. I try to do `from pydbus import SessionBus` in a shell (inside the scrobbler venv) and I get an import error.
```python
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/kroot/.virtualenvs/trakt-scrobbler-XL06I9Vp-py3.9/lib/python3.9/site-packages/pydbus/__init__.py", line 1, in <module>
    from .bus import SystemBus, SessionBus, connect
  File "/home/kroot/.virtualenvs/trakt-scrobbler-XL06I9Vp-py3.9/lib/python3.9/site-packages/pydbus/bus.py", line 1, in <module>
    from gi.repository import Gio
ModuleNotFoundError: No module named 'gi'
```

It seems the pydbus module still depends on `gi`?

2021-01-17 06:59 UTC, ahmubashshir commented
> There's some trouble in my setup it seems. I try to do `from pydbus import SessionBus` in a shell (inside the scrobbler venv) and I get an import error.
> 
> ```python
> Traceback (most recent call last):
>   File "<console>", line 1, in <module>
>   File "/home/kroot/.virtualenvs/trakt-scrobbler-XL06I9Vp-py3.9/lib/python3.9/site-packages/pydbus/__init__.py", line 1, in <module>
>     from .bus import SystemBus, SessionBus, connect
>   File "/home/kroot/.virtualenvs/trakt-scrobbler-XL06I9Vp-py3.9/lib/python3.9/site-packages/pydbus/bus.py", line 1, in <module>
>     from gi.repository import Gio
> ModuleNotFoundError: No module named 'gi'
> ```
> 
> It seems the pydbus module still depends on `gi`?

I switched to jeepney(a pure python implementation of libdbus)

2021-01-17 07:16 UTC, iamkroot approved these changes

2021-01-17 07:17 UTC, iamkroot commented
I'll wait a bit before merging this. Want to finish releasing v1.2.0 stable before merging this to master.

2021-01-17 07:37 UTC, merged