trakt_if: Add search retry without 'year'
iamkroot/trakt-scrobbler pull request #130
Opened 2021-07-09 18:07 UTC by JRFarmer

Trakt 'year' metadata will infrequently disagree with other sources. In case search() returns no matches, retry without filtering by year.

Closes #129

2021-07-10 04:57 UTC, iamkroot requested changes

2021-07-10 04:57 UTC, iamkroot commented on trakt_scrobbler/trakt_interface.py
> +        results = search(title, [required_type]) # possible mismatch in metadata, retry without 'year'
Very clean indeed. I would also add a log message (`WARNING` severity seems correct) to track that we found no results the first time, and that we are doing a retry.
Should we also send a notification to the user about this?

2021-07-10 05:01 UTC, iamkroot requested changes

2021-07-10 05:01 UTC, iamkroot commented on trakt_scrobbler/trakt_interface.py
> +    if results == []: # no match
This isn't entirely correct. It is very probable that the `year==None` during the first search itself (happens in other players where metadata is extracted from filenames). 
In this case, we'd be doing a redundant API call, so better to guard against this.

2021-07-11 05:48 UTC, iamkroot requested changes
Almost there!

2021-07-11 05:48 UTC, iamkroot commented on trakt_scrobbler/trakt_interface.py
> +    if (results == [] and year is not None): # no match, possibly a mismatch in year metadata
Parentheses not needed, line length below 88.
```suggestion
    if results == [] and year is not None:
    # no match, possibly a mismatch in year metadata
```

2021-07-11 05:48 UTC, iamkroot commented on trakt_scrobbler/trakt_interface.py
> +        msg = f'Trakt search yielded no results for the {required_type}, {title}, Year: {year}. Retrying search without filtering by year'
I'd prefer this line to be broken up - the line length should not exceed 88 characters. 
```suggestion
        msg = (f'Trakt search yielded no results for the {required_type}, {title}, '
               f'Year: {year}. Retrying search without filtering by year.')
```

2021-07-11 05:48 UTC, iamkroot commented on trakt_scrobbler/trakt_interface.py
> +        results = search(title, [required_type]) # retry without 'year'
Two spaces before the comment.
```suggestion
        results = search(title, [required_type])  # retry without 'year'
```

2021-07-11 05:54 UTC, merged

2021-07-11 05:55 UTC, iamkroot commented
Since they were just some cosmetic changes, I applied the fixes myself and merged the PR. Thanks again!

2021-07-11 12:51 UTC, JRFarmer commented
Glad I could help. It's a nice tool and I hope I can help contribute again in the future!