Add zsh completion
iamkroot/trakt-scrobbler pull request #174
Opened 2022-01-31 21:34 UTC by ahmubashshir

See-also: #173

Signed-off-by: Mubashshir <ahmubashshir@gmail.com>

2022-02-02 04:12 UTC, iamkroot requested changes
Thanks for raising this PR!
While the core completions are fine, I think we should also add instructions on how to actually install them, and also how to generate them for the future.
Maybe add a README file in the same directory?

2022-02-02 04:31 UTC, iamkroot commented on completions/trakts.zsh
> +# shellcheck shell=bash
Nitpick: Shouldn't this be zsh?

2022-02-05 11:39 UTC, ahmubashshir commented
shellcheck only supports sh/bash/ksh, and bash is the most similar to 
zsh (that's why I disabled shellcheck warnings on zsh specific blocks)
	Mubashshir

On Tue, Feb 1 2022 at 08:32:03 PM -0800, Krut Patel 
***@***.***> wrote:
> @iamkroot commented on this pull request.
> 
> In completions/trakts.zsh:
> 
> > @@ -0,0 +1,297 @@
> +#compdef trakts
> +#
> +# Zsh auto complete function for trakts
> +#
> +# shellcheck shell=bash
> Nitpick: Shouldn't this be zsh?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2022-02-05 11:39 UTC, ahmubashshir commented on completions/trakts.zsh
> +# shellcheck shell=bash
shellcheck only supports sh/bash/ksh, and bash is the most similar to
zsh (that's why I disabled shellcheck warnings on zsh specific blocks)

2022-02-05 12:17 UTC, ahmubashshir commented
BTW, we can submit the completion to [zsh-completions](https://github.com/zsh-users/zsh-completions) too.

2022-02-09 03:42 UTC, iamkroot approved these changes

2022-02-09 03:43 UTC, merged

2022-02-09 03:43 UTC, iamkroot commented
Thanks for the effort @ahmubashshir! :)