Character encoding & windows fixes
iamkroot/trakt-scrobbler pull request #208
Opened 2022-09-06 10:59 UTC by Sp3EdeR

Closes #205 

* Fixed the MPC-HC data encoding issue
* Fixed the whitelist not matching paths on Windows

2022-09-10 07:44 UTC, iamkroot reviewed
Thanks for making the PR! I feel that this approach is a bit too hacky. 
1. Ideally, the HTTP library (`requests`) should be doing the decoding. We shouldn't have to do it manually. I'll try to look into why this isn't working out of the box.
2. Parsing complex HTML using Regexes is a recipe for disaster. I'd prefer to use something like BeautifulSoup or the lxml package for this.

2022-09-10 08:10 UTC, Sp3EdeR commented
> Thanks for making the PR! I feel that this approach is a bit too hacky.
> 
> 1. Ideally, the HTTP library (`requests`) should be doing the decoding. We shouldn't have to do it manually. I'll try to look into why this isn't working out of the box.
> 2. Parsing complex HTML using Regexes is a recipe for disaster. I'd prefer to use something like BeautifulSoup or the lxml package for this.

HTTP does not know HTML, since HTTP can transmit any number of documents. It is of course possible to add a full-on HTML parser library. I did write the regex to be standard-compliant though, so I would expect it to be much more robust than the existing `<p>` parser at this point. Since the script needs to deal with just a specific program's output only, perhaps this might still be the smallest impact.

2024-01-24 06:42 UTC, iamkroot commented on trakt_scrobbler/file_info.py
> +def normPath(path):
This should be unnecessary with the latest commit in master.

2024-01-24 06:43 UTC, iamkroot commented on trakt_scrobbler/player_monitors/mpc.py
> +    CHARSET_PATTERN = re.compile(r'''<\s*meta\s+[^>]*charset\s*=\s*(?:['"]([^'"]+)['"]|([^\s]+))\s*[^>]*>''')
Maybe we could try using the [xml.etree.ElementTree](https://docs.python.org/3.12/library/xml.etree.elementtree.html#module-xml.etree.ElementTree) parser here? I've not tested if it can handle the HTML here.

2024-01-24 06:44 UTC, iamkroot requested changes

2024-01-24 06:44 UTC, iamkroot commented on trakt_scrobbler/player_monitors/mpc.py
> +    def _decodeResponseContent(self, response):
Please use `snake_case` for the method names

2024-01-24 19:04 UTC, Sp3EdeR commented on trakt_scrobbler/player_monitors/mpc.py
> +    CHARSET_PATTERN = re.compile(r'''<\s*meta\s+[^>]*charset\s*=\s*(?:['"]([^'"]+)['"]|([^\s]+))\s*[^>]*>''')
The MPC-HC web page does not evaluate to a valid XML (unterminated tags), so that cannot be used. The meta charset tag really cannot be expressed in any different way than what the regexp parses (see the spec: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#charset), and the rest of the page doesn't really need to be parsed for this feature...

2024-01-25 14:38 UTC, iamkroot commented on trakt_scrobbler/player_monitors/mpc.py
> +    CHARSET_PATTERN = re.compile(r'''<\s*meta\s+[^>]*charset\s*=\s*(?:['"]([^'"]+)['"]|([^\s]+))\s*[^>]*>''')
Now that I think about it... We shouldn't care about extracting the `charset` much. Is there any way that the value will be anything other than `utf-8`? It has pretty much become the standard.
I say we can just assume that's what it'll be and do the decode accordingly.

This is all because I'm just afraid of such complex regexes. I understand you're saying that it the only way to parse this tag, but I have no way to exhaustively find all the strings it can match and verify. I would much rather go with hardcoding `utf-8` for now.

2024-01-25 17:42 UTC, Sp3EdeR commented on trakt_scrobbler/player_monitors/mpc.py
> +    CHARSET_PATTERN = re.compile(r'''<\s*meta\s+[^>]*charset\s*=\s*(?:['"]([^'"]+)['"]|([^\s]+))\s*[^>]*>''')
I wanted to parse the charset because MPC-HC is an old software with multiple forks, so it is hard to figure out whether all versions used utf-8 encoding on the web interface. So while utf8 is certainly the de-facto standard, I'm not sure if the various versions of MPC compy. But I did just check the latest code of main MPC-HC, the clsid2 fork, and MPC-BE and they all use utf-8, so I guess hard-coding it is fine by me! :)

Just a disclaimer - I wasn't saying that the regex is the only way to parse it in a standard way. It could be parsed with an HTML parser and then matched with a CSS matcher. That would just be a way too huge tooling to achieve a very simple task, and I don't think it would be worth it.

2024-01-25 18:09 UTC, Sp3EdeR commented
I've updated the PR according to the review comments.

2024-01-31 04:19 UTC, iamkroot approved these changes
Thanks for the simplification!

2024-01-31 04:19 UTC, merged