Handle `int` declared as `str` for `match.episode` on remaps
iamkroot/trakt-scrobbler pull request #295
Opened 2024-05-12 00:10 UTC by BrutuZ

### What Happens
trakt-scrobbler silently crashes with the following entry to `remap_rules.toml`:
```toml
[[rules]]
match.title = "Doctor Who"
match.year = 2005
match.episode = "168"
match.season = 0
id.trakt_slug = "doctor-who-2024"
type = "episode"
episode_delta = -164
```

### What Should Happen
Parser should gracefully handle a single episode declared as a string.

### What changed
Added `TypeError` to the caught exceptions as groups contained in a part of the expression that don't match (`m["end"]`) return a `NoneType` ([docs](https://docs.python.org/3/library/re.html#re.Match.group)) which causes the `int()` operation fail instead of the mapping.

2024-05-18 21:27 UTC, BrutuZ commented
Added a commit to handle (ignore) the odd anonymous Plex sessions.
Sometimes when streaming the session won't have a user name, it will look empty even on the server dashboard. Not sure if it's a side-effect of streaming via PlexKodiConnect but regardless, this is the expected behavior instead of raising an exception every few seconds

2024-05-19 15:49 UTC, iamkroot commented on trakt_scrobbler/player_monitors/plex.py
> +            if metadata["User"].get("title") == self.config["scrobble_user"]:
I didn't know the title field is optional. If so, how's the user name sent?

2024-05-19 15:51 UTC, iamkroot requested changes

2024-05-19 15:51 UTC, iamkroot commented on trakt_scrobbler/mediainfo_remap.py
> +            except (KeyError, TypeError):
This doesn't seem like the correct way to solve this. We are relying on the fact that the TypeError catch block will set `start=end`. Instead, we should explicitly check for empty `end`.

2024-05-19 16:53 UTC, BrutuZ commented on trakt_scrobbler/player_monitors/plex.py
> +            if metadata["User"].get("title") == self.config["scrobble_user"]:
It shouldn't be, I believe it may be a ~bug~ "unanticipated feature" on Plex.

When it happens the name isn't sent at all, as I mentioned even the dashboard can't tell who is playing the stream, it only shows the default/placeholder profile picture without any text where the name would be.

2024-05-19 17:02 UTC, BrutuZ commented on trakt_scrobbler/mediainfo_remap.py
> +            except (KeyError, TypeError):
I could've checked for empty instead and actually did at first, but realized this was more efficient as `start=end` is the intended result since it will return the same as if it was a `int` in the previous `if` block

2024-05-20 19:57 UTC, BrutuZ commented on trakt_scrobbler/mediainfo_remap.py
> +            except (KeyError, TypeError):
Switched to a ternary check instead

2024-06-13 06:03 UTC, iamkroot approved these changes
Thanks for taking the time to contribute!

2024-06-13 06:04 UTC, merged